services:
  debian-node-webapp.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/debian-node-webapp.development
      dockerfile: with-user.Dockerfile
    user: "${UID:-0}:${GID:-0}"
  node-firebase.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/node-firebase.development
      dockerfile: with-user.Dockerfile
    command:
      - bash
      - -c
      - |
        echo npm install
    environment:
      - FIREBASE_TOKEN
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:3000:3000"
      # see https://firebase.google.com/docs/emulator-suite/install_and_configure#port_configuration
      - "${BIND_IP_ADDR:-127.0.0.1}:5000:5000"
      - "${BIND_IP_ADDR:-127.0.0.1}:5001:5001"
      - "${BIND_IP_ADDR:-127.0.0.1}:8080:8080"
      - "${BIND_IP_ADDR:-127.0.0.1}:8085:8085"
      - "${BIND_IP_ADDR:-127.0.0.1}:9000:9000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/workspace
    working_dir: /workspace
  node-webapp.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/node-webapp.development
      dockerfile: with-user.Dockerfile
    user: "${UID:-0}:${GID:-0}"
  provisioning:
    build:
      args:
        DOCKER_GID: ${DOCKER_GID}
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/provisioning
      dockerfile: with-user.Dockerfile
    user: "${UID:-0}:${GID:-0}"
  python-app.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/python-app.development
      dockerfile: with-user.Dockerfile
    user: "${UID:-0}:${GID:-0}"
  ruby-webapp.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/ruby-webapp.development
      dockerfile: with-user.Dockerfile
    user: "${UID:-0}:${GID:-0}"
version: "3.8"
