services:
  node-firebase:
    build:
      context: Dockerfile.d/node-firebase.development
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    command:
      - bash
      - -c
      - |
        npm install
    environment:
      - FIREBASE_TOKEN
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:3000:3000"
      # see https://firebase.google.com/docs/emulator-suite/install_and_configure#port_configuration
      - "${BIND_IP_ADDR:-127.0.0.1}:5000:5000"
      - "${BIND_IP_ADDR:-127.0.0.1}:5001:5001"
      - "${BIND_IP_ADDR:-127.0.0.1}:8080:8080"
      - "${BIND_IP_ADDR:-127.0.0.1}:8085:8085"
      - "${BIND_IP_ADDR:-127.0.0.1}:9000:9000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/workspace
    working_dir: /workspace
version: "3.7"
