name: default
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: docker build Dockerfile.d/node-firebase.development
