name: publish-go-app-development-container-images

env:
  IMAGE_NAME: go-app.development
  LANGUAGE_VERSION_ARG_KEY: _GO_VERSION
  LANGUAGE_VERSIONS_CSV: 1.22

on:
  push:
    paths:
      - ".github/workflows/**"
      - "compose.yaml"
      - "code-stubs/go-app/**"
      - "Dockerfile.d/go-app.development/**"
  workflow_dispatch:

jobs:
  set-environment-variable-as-vars:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.set-outputs.outputs.image-name }}
      language-version-arg-key: ${{ steps.set-outputs.outputs.language-version-arg-key }}
      language-versions-csv: ${{ steps.set-outputs.outputs.language-versions-csv }}
    steps:
      - id: set-outputs
        run: |
          echo 'image-name=${{ env.IMAGE_NAME }}' >> $GITHUB_OUTPUT
          echo 'language-version-arg-key=${{ env.LANGUAGE_VERSION_ARG_KEY }}' >> $GITHUB_OUTPUT
          echo 'language-versions-csv=${{ env.LANGUAGE_VERSIONS_CSV }}' >> $GITHUB_OUTPUT
  test-containers:
    name: test-containers - ${{ needs.set-environment-variable-as-vars.outputs.image-name }}
    needs:
      - set-environment-variable-as-vars
    secrets: inherit
    uses: ./.github/workflows/_start-stop-the-container.yaml
    with:
      compose-service-name: "${{ needs.set-environment-variable-as-vars.outputs.image-name }}"
      language-versions-csv: "${{ needs.set-environment-variable-as-vars.outputs.language-versions-csv }}"
  publish-containers:
    name: publish-containers - ${{ needs.set-environment-variable-as-vars.outputs.image-name }}
    needs:
      - set-environment-variable-as-vars
    secrets: inherit
    uses: ./.github/workflows/_publish-the-container-image.yaml
    with:
      image-name: "${{ needs.set-environment-variable-as-vars.outputs.image-name }}"
      language-version-arg-key: "${{ needs.set-environment-variable-as-vars.outputs.language-version-arg-key }}"
      language-versions-csv: "${{ needs.set-environment-variable-as-vars.outputs.language-versions-csv }}"
