name: publish-node-webapp-development-container-images

env:
  IMAGE_NAME: node-webapp.development

on:
  push:
    paths:
      - ".github/workflows/**"
      - "compose.yaml"
      - "code-stubs/node-webapp/**"
      - "Dockerfile.d/node-webapp.development/**"
  workflow_dispatch:

jobs:
  set-environment-variable-as-vars:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.set-outputs.outputs.image-name }}
    steps:
      - id: set-outputs
        run: |
          echo 'image-name=${{ env.IMAGE_NAME }}' >> $GITHUB_OUTPUT
  test-containers:
    name: test-containers - ${{ needs.set-environment-variable-as-vars.outputs.image-name }}
    needs:
      - set-environment-variable-as-vars
    secrets: inherit
    # uses: mazgi/container-images/.github/workflows/_start-stop-the-container.yaml@main
    uses: mazgi/dockerfiles/.github/workflows/_start-stop-the-container.yaml@main
    with:
      compose-service-name: "${{ needs.set-environment-variable-as-vars.outputs.image-name }}"
  publish-containers:
    name: publish-containers - ${{ needs.set-environment-variable-as-vars.outputs.image-name }}
    needs:
      - set-environment-variable-as-vars
    secrets: inherit
    # uses: mazgi/container-images/.github/workflows/_publish-the-container-image.yaml@main
    uses: mazgi/dockerfiles/.github/workflows/_publish-the-container-image.yaml@main
    with:
      image-name: "${{ needs.set-environment-variable-as-vars.outputs.image-name }}"
