name: publish-docker-images
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
on:
  push:
    paths:
      - "Dockerfile.d/**"

jobs:
  build:
    strategy:
      matrix:
        # See: https://github.com/actions/virtual-environments
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: detect contexts that changed
        run: >
          jq --raw-output --slurp '[.[][]] 
          | map(select(. | match("^Dockerfile\\.d/"))) 
          | map(. |= (gsub("Dockerfile\\.d/(?<context>[^/]*)/.*"; "Dockerfile.d/\(.context)"))) 
          | unique 
          | .[]' 
          $HOME/files_{added,modified}.json
      - run: echo ::set-env name=SHORT_SHA::$(echo '${{ toJSON(github) }}' | jq -r '.sha[0:7]')
      - name: build each docker context
        run: |
          for context in $(jq --raw-output --slurp '[.[][]] 
          | map(select(. | match("^Dockerfile\\.d/"))) 
          | map(. |= (gsub("Dockerfile\\.d/(?<context>[^/]*)/.*"; "Dockerfile.d/\(.context)"))) 
          | unique 
          | .[]' \
          $HOME/files_{added,modified}.json)
          do
            echo "CONTEXT: $context" #Dockerfile.d/ruby-webapp.development
            TAG=ghcr.io/${{ github.repository_owner }}/$(basename $context):$(date +%Y%m-)$SHORT_SHA
            echo $TAG
            docker build --tag $TAG $context
          done
