name: test-dockerfiles
# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
on:
#   push:
#     paths:
#       - "Dockerfile.d/**"

jobs:
  detect:
    outputs:
      changed-contexts: ${{ steps['detected-context-paths'].outputs['changed-contexts'] }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Install Docker for Mac
      #   run: brew install docker docker-compose docker-machine
      #   if: runner.os == 'macOS'
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: detect contexts that changed
        run: >
          jq --compact-output --slurp '[.[][]] 
          | map(select(. | match("^Dockerfile\\.d/"))) 
          | map(. |= (gsub("Dockerfile\\.d/(?<context>[^/]*)/.*"; "Dockerfile.d/\(.context)"))) 
          | unique' 
          $HOME/files_{added,modified}.json > $HOME/changed_contexts.json
      - id: detected-context-paths
        run: echo "::set-output name=changed-contexts::$(cat $HOME/changed_contexts.json)"
  build:
    needs:
      - detect
    strategy:
      matrix:
        # See: https://github.com/actions/virtual-environments
        os: [ubuntu-latest]
        target-context: ${{ fromJson(needs.detect.outputs['changed-contexts']) }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.target-context }}
      - name: build each docker context that was changed
        run: |
          docker build ${{ matrix.target-context }}
