name: test-dockerfiles
on: [push]

jobs:
  build:
    strategy:
      matrix:
        # See: https://github.com/actions/virtual-environments
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # - name: Install Docker for Mac
      #   run: brew install docker docker-compose docker-machine
      #   if: runner.os == 'macOS'
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.4
      - name: detect contexts that changed
        run: >
          jq --raw-output --slurp '[.[][]] 
          | map(select(. | match("^Dockerfile\\.d/"))) 
          | map(. |= (gsub("Dockerfile\\.d/(?<context>[^/]*)/.*"; "Dockerfile.d/\(.context)"))) 
          | unique 
          | .[]' 
          $HOME/files_{added,modified}.json
      - name: build each docker context
        run: |
          for context in $(jq --raw-output --slurp '[.[][]] 
          | map(select(. | match("^Dockerfile\\.d/"))) 
          | map(. |= (gsub("Dockerfile\\.d/(?<context>[^/]*)/.*"; "Dockerfile.d/\(.context)"))) 
          | unique 
          | .[]' \
          $HOME/files_{added,modified}.json)
          do
            echo "CONTEXT: $context"
            docker build $context
          done
